Controllers/MultiplayerController.cs
using practica_1.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace practica_1.Controllers
{
    public class MultiplayerController : Controller
    {
        // GET: Multiplayer
        public ActionResult Index()
        {
            if (Session["actualUser"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            if (Session["MultiplayerGame"] == null)
            {
                var tempUser = (Account)Session["actualUser"];
                var initialGame = new Game
                {
                    BlackPoints = 2,
                    WhitePoints = 2,
                    GameBoard = new Board(8, 8, "classic", false),
                    Player1 = tempUser,
                    ActualTurn = "negro",
                };
                //initialGame.GameBoard.DisplayValidMoves(initialGame.ActualTurn);
                Session["MultiplayerGame"] = initialGame;
            }
            //t.Start();
            return View(Session["MultiplayerGame"]);
        }

        public ActionResult UpdateBoard(int row, int column)
        {
            var game = (Game)Session["MultiplayerGame"];
            game.GameBoard.GameBoard[row, column].Color = game.ActualTurn;
            game.GameBoard.GameBoardString[row, column] = game.ActualTurn;
            if (game.GameBoard.CustomOpening && game.GameBoard.CustomOpeningPieces < 4)
                game.GameBoard.CustomOpeningPieces++;
            game.AddMovementToList(column, row);
            game.GameBoard.CleanBoard();
            game.GameBoard.FlipCoins(game.ActualTurn, row, column); 
            game.UpdateTurn();
            game.GameBoard.DisplayValidMoves(game.ActualTurn);
            game.CountPoints();

            if (game.IsGameOver())
            {
                if (game.ReverseScore)
                {
                    if (game.WhitePoints < game.BlackPoints)
                        TempData["message"] = "El ganador es Blanco";
                    else if (game.BlackPoints < game.WhitePoints)
                        TempData["message"] = "El ganador es  Negro";
                    else
                        TempData["message"] = "El resultado final es empate";
                }
                else
                {
                    if (game.WhitePoints > game.BlackPoints)
                        TempData["message"] = "El ganador es Blanco";
                    else if (game.BlackPoints > game.WhitePoints)
                        TempData["message"] = "El ganador es  Negro";
                    else
                        TempData["message"] = "El resultado final es empate";
                }

                game.SaveToDB();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult NewGame(string username, string mode1, string mode2)
        {
            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index");
            }
            var tempUser = (Account)Session["actualUser"];
            var initialGame = new Game
            {
                BlackPoints = 2,
                WhitePoints = 2,
                GameBoard = new Board(8, 8, "classic", false),
                Player1 = tempUser,
                Player2 = new Account { Username = username },
                ActualTurn = "negro",
            };
            if (!string.IsNullOrEmpty(mode1))
                if (mode1 == "custom_opening")
                    initialGame = new Game
                    {
                        BlackPoints = 2,
                        WhitePoints = 2,
                        GameBoard = new Board(8, 8, "custom_opening", false),
                        Player1 = tempUser,
                        Player2 = new Account { Username = username },
                        ActualTurn = "negro",
                    };
            if (!string.IsNullOrEmpty(mode2))
                if (mode2 == "reverse_score")
                    initialGame.ReverseScore = true;
            initialGame.GameBoard.DisplayValidMoves(initialGame.ActualTurn);
            Session["MultiplayerGame"] = initialGame;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
                try
                {
                    var gameBoard = (string[,])Session["gameBoard"];
                    //string path = Path.Combine(Server.MapPath("~/Games"),
                    //                           Path.GetFileName(file.FileName));
                    //file.SaveAs(path);
                    XmlDocument xmlDocument = new XmlDocument();
                    List<Disk> movesDone = new List<Disk>();
                    xmlDocument.Load(file.InputStream);
                    XmlNodeList diskNodes = xmlDocument.SelectNodes("tablero/ficha");
                    foreach (XmlNode disk in diskNodes)
                    {
                        int Column = 0;
                        var diskItem = new Disk()
                        {
                            Color = disk["color"].InnerText,
                            Column = disk["columna"].InnerText,
                            Row = disk["fila"].InnerText,
                        };

                        switch (diskItem.Column)
                        {
                            case "A":
                                Column = 0;
                                break;
                            case "B":
                                Column = 1;
                                break;
                            case "C":
                                Column = 2;
                                break;
                            case "D":
                                Column = 3;
                                break;
                            case "E":
                                Column = 4;
                                break;
                            case "F":
                                Column = 5;
                                break;
                            case "G":
                                Column = 6;
                                break;
                            case "H":
                                Column = 7;
                                break;
                            default:
                                break;
                        }
                        int Row = int.Parse(disk["fila"].InnerText) - 1;
                        gameBoard[Row, Column] = diskItem.Color;
                        movesDone.Add(diskItem);
                    }

                    foreach (var move in movesDone)
                    {
                        int colNumber = 0;
                        int rowNumber = Convert.ToInt32(move.Row) - 1;
                        switch (move.Column)
                        {
                            case "A":
                                colNumber = 0;
                                break;
                            case "B":
                                colNumber = 1;
                                break;
                            case "C":
                                colNumber = 2;
                                break;
                            case "D":
                                colNumber = 3;
                                break;
                            case "E":
                                colNumber = 4;
                                break;
                            case "F":
                                colNumber = 5;
                                break;
                            case "G":
                                colNumber = 6;
                                break;
                            case "H":
                                colNumber = 7;
                                break;
                            default:
                                break;
                        }
                        var ari = TokenPositionValid(colNumber - 1, rowNumber - 1, gameBoard);
                        var ar = TokenPositionValid(colNumber, rowNumber - 1, gameBoard);
                        var ard = TokenPositionValid(colNumber + 1, rowNumber - 1, gameBoard);

                        var i = TokenPositionValid(colNumber - 1, rowNumber, gameBoard);
                        var d = TokenPositionValid(colNumber + 1, rowNumber, gameBoard);

                        var abi = TokenPositionValid(colNumber - 1, rowNumber + 1, gameBoard);
                        var ab = TokenPositionValid(colNumber, rowNumber + 1, gameBoard);
                        var abd = TokenPositionValid(colNumber + 1, rowNumber + 1, gameBoard);
                        if (!ari && !ar && !ard && !abi && !ab && !abd && !i && !d)
                        {
                            gameBoard[rowNumber, colNumber] = " ";
                        }
                    }
                    XmlNode nextTurn = xmlDocument.SelectSingleNode("tablero/siguienteTiro");

                    string actualTurn = nextTurn["color"].InnerText;
                    actualTurn = actualTurn.Replace(" ", string.Empty);
                    Session["actualTurn"] = actualTurn;
                    ViewBag.ActualTurn = Session["actualTurn"].ToString();
                    
                    Session["movesDone"] = movesDone;
                    ViewBag.Message = "Archivo cargado exitosamente";
                    var validMoves = CalculateValidMoves(actualTurn, gameBoard);
                    for (int i = 0; i < 8; i++)
                        for (int j = 0; j < 8; j++)

Views/Multiplayer/Index.cshtml
<div class="bd-example bd-example-tabs">
    <div class="row">
        <div class="col-3">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <p class="nav-link">Opciones Partida vs CPU</p>
                <a class="nav-link" id="v-pills-home-tab"       href="@Url.Action("index", "Home")"  role="tab" aria-controls="v-pills-home" aria-selected="false">Nueva Partida</a>
                <a class="nav-link" id="v-pills-profile-tab"    href="#v-pills-upload" role="tab" aria-controls="v-pills-profile" aria-selected="false">Cargar Partida</a>
                <a class="nav-link" id="v-pills-messages-tab"   href="#v-pills-download" role="tab" aria-controls="v-pills-messages" aria-selected="false">Descargar Partida</a>
                <p class="nav-link">Opciones Partida Jugador vs Jugador</p>
                <a class="nav-link" id="v-pills-home-tab-pvp"       data-toggle="pill"   href="#v-pills-home-pvp"    role="tab" aria-controls="v-pills-home" aria-selected="false">Nueva Partida</a>
                <a class="nav-link" id="v-pills-profile-tab-pvp"    data-toggle="pill"  href="#v-pills-profile-pvp"  role="tab" aria-controls="v-pills-profile" aria-selected="false">Cargar Partida</a>
                <a class="nav-link" id="v-pills-messages-tab-pvp"   data-toggle="pill"  href="#v-pills-messages-pvp" role="tab" aria-controls="v-pills-messages" aria-selected="false">Descargar Partida</a>
            </div>
        </div>
        <div class="col-9">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-home-pvp" role="tabpanel" aria-labelledby="v-pills-home-tab">@Html.Partial("_HomeBoardMultiplayer")</div>
                <div class="tab-pane fade" id="v-pills-profile-pvp" role="tabpanel" aria-labelledby="v-pills-profile-tab">@Html.Partial("_HomeUploadFile")</div>
                <div class="tab-pane fade" id="v-pills-messages-pvp" role="tabpanel" aria-labelledby="v-pills-messages-tab">@Html.Partial("_HomeDownloadFile")</div>

            </div>
        </div>
    </div>
</div>

Views/Multiplayer/_HomeBoardMultiplayer.cshtml
@using practica_1.Models;
    <div class="container-fluid">
        @using (Html.BeginForm("NewGame", "Multiplayer", FormMethod.Post))
        {
            <label for="username">Nombre de Usuario:</label><br>
            <input type="text" name="username" id="username" /><br>
            <input type="checkbox" id="mode1" name="mode1" value="custom_opening">
            <label for="mode1"> Usar Apertura Personalizada</label><br>

            <input type="checkbox" id="mode2" name="mode2" value="reverse_score">
            <label for="mode2"> Usar Punteo Inverso</label><br>
                <button type="submit">Iniciar Partida</button>
        }

    <h2>Turno Actual: @Model.ActualTurn</h2>
        @if (TempData["message"] != null)
        {
            <script type="text/javascript">

            window.onload = function () {
                alert("@TempData["message"]");
            };
            </script>

        }
        <table class="table justify-content-center">
            <thead>
                <tr>
                    <th>
                        Blanco: @Model.WhitePoints
                    </th>
                    <th>
                        Negro: @Model.BlackPoints
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Tiempo Blanco: <p id="WhiteTimer"></p>
                    </td>
                    <td>
                        Tiempo Negro: <p id="WhiteTimer"></p>
                    </td>
                </tr>
            </tbody>
        </table>

        <table class="table justify-content-center w-100 h-100">
            <tbody>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">A</th>
                    <th scope="col">B</th>
                    <th scope="col">C</th>
                    <th scope="col">D</th>
                    <th scope="col">E</th>
                    <th scope="col">F</th>
                    <th scope="col">G</th>
                    <th scope="col">H</th>
                    <th scope="col"></th>
                </tr>
                @{string full_path = "";}
                @for (int i = 1; i < Model.GameBoard.Rows + 1; i++)
                {
                    <tr class="table-success">
                        <th scope="row">@i</th>
                        @for (int j = 0; j < Model.GameBoard.Columns; j++)
                        {
                            if (Model.GameBoard.GameBoard[i - 1, j].Color != " ")
                            {
                                if (Model.GameBoard.GameBoard[i - 1, j].Color == "posible")
                                {
                                    full_path = "/Content/Images/disk-" + Model.GameBoard.GameBoard[i - 1, j].Color + ".png";
                                    <td><a href='@Url.Action("UpdateBoard", "Multiplayer", new {Row = i-1, Column =j})'><img src="@full_path"></a></td>
                                }
                                else
                                {
                                    full_path = "/Content/Images/disk-" + Model.GameBoard.GameBoard[i - 1, j].Color + ".png";
                                    <td><img src="@full_path"></td>
                                }

                            }
                            else
                            {
                                <td><img src="~/Content/Images/disk.png" /></td>
                            }
                        }
                        <th scope="row">@i</th>
                    </tr>
                }
                <tr>
                    <th scope="col"></th>
                    <th scope="col">A</th>
                    <th scope="col">B</th>
                    <th scope="col">C</th>
                    <th scope="col">D</th>
                    <th scope="col">E</th>
                    <th scope="col">F</th>
                    <th scope="col">G</th>
                    <th scope="col">H</th>
                    <th scope="col"></th>
                </tr>
            </tbody>

        </table>
    </div>

Views/Multiplayer/_HomeDownloadFile.cshtml
@{
    ViewBag.Title = "_HomeDownloadFile";
}

<h2>_HomeDownloadFile</h2>

<a  class="btn btn-default" href='@Url.Action("Download", "Home")'>Descargar Partida</a>

Views/Multiplayer/_HomeUploadFile.cshtml
@using (Html.BeginForm("Upload",
                                "Home",
                                FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Cargar Partida</h2>
    <label for="file">Selecciona un archivo XML</label>
    <input type="file" name="file" id="file" accept="text/xml" />
    <br>
    <br>
    <input type="submit" class="btn btn-default" value="Cargar Partida"/>
    <br>
    <br>
    @ViewBag.Message
}